language: generic
script: ./build/scripts/travis_build

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nasm

sudo: required
dist: trusty

cache:
    directories:
    - prebuilt/downloads

env:
  global:
    # GITHUB_TOKEN
    - secure: mH557eyg2SqDZJS+Bb+rbQ4a+rQ/3ckozNCt1bHCOOjNIZQDHSZdxbUCiT5GV0PUaS7fjSsyYkp53rdFpmuNyyFtIlPmHnEf58/IMoF0wuf4von+XFq7NCl+xxnwOrWye3W71itexdcucGOAl6mR0LqVCb9WYYAf0mrjIDWVOI05b8l++MBY6pr8GhzdwQEtndv7IrRTjf9ujX0RKDsoE9i7Q6bnm07KEpieDTZVcOfIqC/NW4IKbfdVyQj+iAlDRoXFaWTgjbU+Hwk8UlVwgZZf4dbAelhStGKP7kWN+MseJbq+zEE/QeHzJfwAMz4nHrKg6h+cjvc5HW/hgCQc6YZXTHR79tVfKdIw6Bw8i1iMGDB0vBcavSlJGRevUvegvXSFcHVQhggcfayLnpbBP21MnIeIZxD5stosbOjQZZYVLh/IyB6bZCWnoRFD15B5kMmERBHjrVT/mBJAbptVgXVQvH1THFNUORQD00VxzymMY8zinzaZqDSy6sZSlNXb/QpSPBTtG3XqITOVyM8e8x6Y3jMqvl1FPB9uQJT12FUn+PLgPW8PRVWjh++6gE9/wu5H1PK7g6d9Q5N1HWsDZQj5/XKcvVPFd9uAcaaCWg/nwgKaZARyuuSE2zj4JS9U/S/KiJLb3TH5vXSV1GXGQbXEhLanHCKvwLU2ko9hfPg=
    # BINTRAY-API-KEY
    - secure: K9tO/kc6z4gZp55vvbTpqGFdCv8ucQEDorxKQao8FjkDGMWg2J9S8dxzY5vwkGg3LCLorJQkWKEcww5MAUxulwEM3w985ugYGlzz587H+olxLyBQ18u8c1FMqRV5sn8c8oucGKAiBBBxoebAevGDqJGQRH3Y40GxLALJCLd93cQkmP6E619kjhiimXpAqxueYcPmi7V5m/w2O5ispgQt9JqQjTaJvbPyJLKItH6I2o3vZ7qlq1MJLXEdFN8qZekqEt7WR3poWIycygNyO5ashfOpnEtbKy6MBHr4JeG/MJYPMTdwXou/pD+U1gOlGC+WPCudEcS/Uz4wwtj6KCCwCWwhge58CF6Z9iML800jb+s6j/FR5D+lZev6HmbLfu1qC9860g6/u0ss7RdTs6KxbWjay1VJBCWhvo89guF485Y7E1QqxXYkDmNQkmd/NC+JoxzK8rJjtDC2UH+sA5dlQ9jo2rf9hwRsUDzX9wOakmdxP5fiHVpSy3M/HYLd9s0n+222/8E4tNMPZ1DqmU7aCxMZlq7XqWq2qGRGwwf5QTP7J78RUHNil+GUe55VEoCTw7B7q4Dooo3B1IvGdG5aEo7UQVUbDXetkG+AYW7jUo0jeK/IkdbgqplHqt/5uK/osV/5BKGx/kj9m0dRChi6t6ZdsiHU18hgZtoA6r2eizU=
  
before_deploy: ./build/scripts/generate_bintray_descriptor

deploy:
  - provider: script
    script: ./build/scripts/deploy_to_ghpages
    on:
      branch: master
    skip_cleanup: true
  - provider: bintray
    file: ./generated/bintray.json
    user: korli
    key: ${BINTRAY_API_KEY}
    skip_cleanup: true

