language: generic
script: ./build/scripts/travis_build

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nasm

sudo: required
dist: trusty

cache:
    directories:
    - prebuilt/downloads

